# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6998c3de15fc155881982786036e3dd5"
name = "kasweb-tech"
handle = "kasweb-tech"
application_url = "https://mali-back-trail-conflict.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tellos-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,unauthenticated_read_product_listings,write_cart_transforms,write_content,write_draft_orders,write_inventory,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://mali-back-trail-conflict.trycloudflare.com/auth/callback",
  "https://mali-back-trail-conflict.trycloudflare.com/auth/shopify/callback",
  "https://mali-back-trail-conflict.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[app_proxy]
url = "https://mali-back-trail-conflict.trycloudflare.com/app/proxy"
subpath = "kas-variants-1"
prefix = "apps"

[pos]
embedded = false
